# Site settings
title: Zentangent
email: chelsea.lynn.bailey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The musings of a young feminist/artist/engineer
  Buckle up and come along for the ride
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zentangent.com" # the base hostname & protocol for your site
github_username:  c-bailey

# Build settings
markdown: kramdown
